CREATE TYPE ticket_type AS ENUM ('DAY', 'WEEK', 'MONTH', 'YEAR');

CREATE TABLE _user (
id INTEGER PRIMARY KEY,
name VARCHAR(50),
creation_date TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE ticket (
id INTEGER PRIMARY KEY,
user_id VARCHAR(50),
ticket_type ticket_type NOT NULL,
creation_date TIMESTAMP(6) WITHOUT TIME ZONE
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES _user(id) ON DELETE CASCADE
);